### ISSUE TITLE
Java version - Bridges initialization.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges_assignments#21]
User id and authentication need to be swapped

C++ is ok, Java needs to be 
   new Bridges (assn no, user id, app id)

**Comment by krs-world** [comment]
David:
Was this fixed? I am confused. Yesterday, it was complaining, but now using hte userid followed by api key seems to work (Java version)

IF it is fixed, close it.

**Comment by AlecGoncharow** [comment]
This was fixed https://github.com/krs-world/bridges/commit/2b924c71003371b675fd0922738845ad82319fcb
